
var JxlDecoderModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JxlDecoderModule) {
  JxlDecoderModule = JxlDecoderModule || {};


var b;b||(b=typeof JxlDecoderModule !== 'undefined' ? JxlDecoderModule : {});var f,h;b.ready=new Promise(function(a,c){f=a;h=c});var aa=Object.assign({},b),l=(a,c)=>{throw c;},n="object"==typeof window,p="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,u=b.ENVIRONMENT_IS_PTHREAD||!1,v="";function ba(a){return b.locateFile?b.locateFile(a,v):v+a}var x,y,z;
if(r){v=p?require("path").dirname(v)+"/":__dirname+"/";var fs,ca;"function"===typeof require&&(fs=require("fs"),ca=require("path"));x=(c,d)=>{c=ca.normalize(c);return fs.readFileSync(c,d?void 0:"utf8")};z=c=>{c=x(c,!0);c.buffer||(c=new Uint8Array(c));return c};y=(c,d,e)=>{c=ca.normalize(c);fs.readFile(c,function(g,k){g?e(g):d(k.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof C))throw c;});process.on("unhandledRejection",
function(c){throw c;});l=(c,d)=>{if(noExitRuntime)throw process.exitCode=c,d;d instanceof C||D("exiting due to exception: "+d);process.exit(c)};b.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(c){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),c;}global.Worker=a.Worker}else if(n||p)p?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),
_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",r||(x=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},p&&(z=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),y=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;
e.send(null)});r&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var da=console.log.bind(console),ea=console.warn.bind(console);r&&(da=a=>fs.writeSync(1,a+"\n"),ea=a=>fs.writeSync(2,a+"\n"));var fa=b.print||da,D=b.printErr||ea;Object.assign(b,aa);aa=null;b.quit&&(l=b.quit);var E;b.wasmBinary&&(E=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!=typeof WebAssembly&&F("no native wasm support detected");
var G,ha,ia=!1,ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H,ka,la,I,J,ma;u&&(H=b.buffer);var pa=b.INITIAL_MEMORY||78643200;
if(u)G=b.wasmMemory,H=b.buffer;else if(b.wasmMemory)G=b.wasmMemory;else if(G=new WebAssembly.Memory({initial:pa/65536,maximum:pa/65536,shared:!0}),!(G.buffer instanceof SharedArrayBuffer))throw D("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),r&&D("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");G&&(H=G.buffer);pa=H.byteLength;var M=H;H=M;b.HEAP8=ka=new Int8Array(M);b.HEAP16=new Int16Array(M);b.HEAP32=I=new Int32Array(M);b.HEAPU8=la=new Uint8Array(M);b.HEAPU16=new Uint16Array(M);b.HEAPU32=J=new Uint32Array(M);b.HEAPF32=new Float32Array(M);b.HEAPF64=ma=new Float64Array(M);var qa,ra=[],sa=[],ta=[];function ua(){var a=b.preRun.shift();ra.unshift(a)}var N=0,va=null,O=null;
function F(a){if(u)postMessage({cmd:"onAbort",arg:a});else if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";D(a);ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");h(a);throw a;}function wa(){return P.startsWith("data:application/octet-stream;base64,")}var P;P="jxl_decoder.wasm";wa()||(P=ba(P));function xa(){var a=P;try{if(a==P&&E)return new Uint8Array(E);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}catch(c){F(c)}}
function ya(){if(!E&&(n||p)){if("function"==typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return xa()});if(y)return new Promise(function(a,c){y(P,function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return xa()})}var za={};
function C(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Aa(a){(a=Q.W[a])||F();Q.ea(a)}function Ba(a){var c=Q.qa();if(!c)return 6;Q.$.push(c);Q.W[a.V]=c;c.V=a.V;var d={cmd:"run",start_routine:a.ua,arg:a.oa,pthread_ptr:a.V};c.Z=()=>{d.time=performance.now();c.postMessage(d,a.wa)};c.loaded&&(c.Z(),delete c.Z);return 0}function Ca(a){if(u)return R(1,1,a);if(!noExitRuntime){Q.va();if(b.onExit)b.onExit(a);ia=!0}l(a,new C(a))}
function Da(a,c){if(!c&&u)throw Ea(a),"unwind";Ca(a)}
var Q={X:[],$:[],ha:[],W:{},aa:function(){u?Q.sa():Q.ra()},ra:function(){for(var a=4;a--;)Q.ba()},sa:function(){Q.receiveObjectTransfer=Q.ta;Q.threadInitTLS=Q.ga;Q.setExitStatus=Q.fa;noExitRuntime=!1},fa:function(){},va:function(){for(var a of Object.values(Q.W))Q.ea(a);for(a of Q.X)a.terminate();Q.X=[]},ea:function(a){var c=a.V;delete Q.W[c];Q.X.push(a);Q.$.splice(Q.$.indexOf(a),1);a.V=0;Fa(c)},ta:function(){},ga:function(){Q.ha.forEach(a=>a())},da:function(a,c){a.onmessage=d=>{d=d.data;var e=d.cmd;
a.V&&(Q.pa=a.V);if(d.targetThread&&d.targetThread!=S()){var g=Q.W[d.ya];g?g.postMessage(d,d.transferList):D('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===e)Ga(d.queue);else if("spawnThread"===e)Ba(d);else if("cleanupThread"===e)Aa(d.thread);else if("killThread"===e)d=d.thread,e=Q.W[d],delete Q.W[d],e.terminate(),Fa(d),Q.$.splice(Q.$.indexOf(e),1),e.V=0;else if("cancelThread"===e)Q.W[d.thread].postMessage({cmd:"cancel"});
else if("loaded"===e)a.loaded=!0,c&&c(a),a.Z&&(a.Z(),delete a.Z);else if("print"===e)fa("Thread "+d.threadId+": "+d.text);else if("printErr"===e)D("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("setimmediate"===d.target)a.postMessage(d);else if("onAbort"===e){if(b.onAbort)b.onAbort(d.arg)}else e&&D("worker sent an unknown command "+e);Q.pa=void 0};a.onerror=d=>{D("worker sent an error! "+d.filename+":"+d.lineno+": "+d.message);throw d;};r&&(a.on("message",
function(d){a.onmessage({data:d})}),a.on("error",function(d){a.onerror(d)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:b.mainScriptUrlOrBlob||_scriptDir,wasmMemory:G,wasmModule:ha})},ba:function(){var a=ba("jxl_decoder.worker.js");Q.X.push(new Worker(a))},qa:function(){0==Q.X.length&&(Q.ba(),Q.da(Q.X[0]));return Q.X.pop()}};b.PThread=Q;function T(a){for(;0<a.length;)a.shift()(b)}b.establishStackSpace=function(){var a=S(),c=I[a+44>>2];Ha(c,c-I[a+48>>2]);U(c)};
function Ea(a){if(u)return R(2,0,a);try{Da(a)}catch(c){c instanceof C||"unwind"==c||l(1,c)}}var W=[];function Ia(a){var c=W[a];c||(a>=W.length&&(W.length=a+1),W[a]=c=qa.get(a));return c}b.invokeEntryPoint=function(a,c){a=Ia(a)(c);noExitRuntime?Q.fa(a):Ja(a)};
function Ka(a){this.Y=a-24;this.na=function(c){J[this.Y+4>>2]=c};this.la=function(c){J[this.Y+8>>2]=c};this.ma=function(){I[this.Y>>2]=0};this.ka=function(){ka[this.Y+12>>0]=0};this.ia=function(){ka[this.Y+13>>0]=0};this.aa=function(c,d){this.ja();this.na(c);this.la(d);this.ma();this.ka();this.ia()};this.ja=function(){J[this.Y+16>>2]=0}}var La=0;function Ma(a,c,d,e){return u?R(3,1,a,c,d,e):Na(a,c,d,e)}
function Na(a,c,d,e){if("undefined"==typeof SharedArrayBuffer)return D("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var g=[];if(u&&0===g.length)return Ma(a,c,d,e);a={ua:d,V:a,oa:e,wa:g};return u?(a.xa="spawnThread",postMessage(a,g),0):Ba(a)}function Ga(a){Atomics.store(I,a>>2,1);S()&&Oa(a);Atomics.compareExchange(I,a>>2,1,0)}b.executeNotifiedProxyingQueue=Ga;var X,Pa;
Pa=r?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?()=>performance.now()-b.__performance_now_clock_drift:()=>performance.now();function Qa(a){var c=Y();a=a();U(c);return a}function R(a,c){var d=arguments.length-2,e=arguments;return Qa(()=>{for(var g=Ra(8*d),k=g>>3,w=0;w<d;w++)ma[k+w]=e[2+w];return Ta(a,d,g,c)})}var Ua=[];function Va(a){return u?R(4,1,a):52}function Wa(a,c,d,e,g){return u?R(5,1,a,c,d,e,g):70}var Xa=[null,[],[]];
function Ya(a,c,d,e){if(u)return R(6,1,a,c,d,e);for(var g=0,k=0;k<d;k++){var w=J[c>>2],V=J[c+4>>2];c+=8;for(var K=0;K<V;K++){var L=la[w+K],na=Xa[a];if(0===L||10===L){L=1===a?fa:D;var q=na;for(var t=0,A=t+NaN,B=t;q[B]&&!(B>=A);)++B;if(16<B-t&&q.buffer&&ja)q=ja.decode(q.buffer instanceof SharedArrayBuffer?q.slice(t,B):q.subarray(t,B));else{for(A="";t<B;){var m=q[t++];if(m&128){var oa=q[t++]&63;if(192==(m&224))A+=String.fromCharCode((m&31)<<6|oa);else{var Sa=q[t++]&63;m=224==(m&240)?(m&15)<<12|oa<<6|
Sa:(m&7)<<18|oa<<12|Sa<<6|q[t++]&63;65536>m?A+=String.fromCharCode(m):(m-=65536,A+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else A+=String.fromCharCode(m)}q=A}L(q);na.length=0}else na.push(L)}g+=V}J[e>>2]=g;return 0}Q.aa();
var Za=[null,Ca,Ea,Ma,Va,Wa,Ya],db={w:function(a){return $a(a+24)+24},v:function(a,c,d){(new Ka(a)).aa(c,d);La++;throw a;},r:function(a){ab(a,!p,1,!n);Q.ga()},e:function(a){u?postMessage({cmd:"cleanupThread",thread:a}):Aa(a)},o:Na,p:function(){return 2097152},q:function(a,c,d,e){if(a==c)setTimeout(()=>Ga(e));else if(u)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:e});else{a=Q.W[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:e})}return 1},t:function(){return-1},m:function(){throw Infinity;
},b:function(){F("")},f:function(){if(!r&&!p){var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";X||(X={});X[a]||(X[a]=1,r&&(a="warning: "+a),D(a))}},c:Pa,h:function(a,c,d){la.copyWithin(a,c,c+d)},s:function(a,c,d){Ua.length=c;d>>=3;for(var e=0;e<c;e++)Ua[e]=ma[d+e];return(0>a?za[-a-1]:Za[a]).apply(null,Ua)},n:function(){F("OOM")},g:function(){throw"unwind";},k:Da,u:Va,l:Wa,d:Ya,j:bb,i:cb,a:G||b.wasmMemory};
(function(){function a(g,k){b.asm=g.exports;Q.ha.push(b.asm.H);qa=b.asm.E;sa.unshift(b.asm.x);ha=k;if(!u){var w=Q.X.length;Q.X.forEach(function(V){Q.da(V,function(){if(!--w&&(N--,b.monitorRunDependencies&&b.monitorRunDependencies(N),0==N&&(null!==va&&(clearInterval(va),va=null),O))){var K=O;O=null;K()}})})}}function c(g){a(g.instance,g.module)}function d(g){return ya().then(function(k){return WebAssembly.instantiate(k,e)}).then(function(k){return k}).then(g,function(k){D("failed to asynchronously prepare wasm: "+
k);F(k)})}var e={a:db};u||(N++,b.monitorRunDependencies&&b.monitorRunDependencies(N));if(b.instantiateWasm)try{return b.instantiateWasm(e,a)}catch(g){D("Module.instantiateWasm callback failed with error: "+g),h(g)}(function(){return E||"function"!=typeof WebAssembly.instantiateStreaming||wa()||P.startsWith("file://")||r||"function"!=typeof fetch?d(c):fetch(P,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(c,function(k){D("wasm streaming compile failed: "+
k);D("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(h);return{}})();b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.x).apply(null,arguments)};b._jxlCreateInstance=function(){return(b._jxlCreateInstance=b.asm.y).apply(null,arguments)};b._jxlDestroyInstance=function(){return(b._jxlDestroyInstance=b.asm.z).apply(null,arguments)};b._free=function(){return(b._free=b.asm.A).apply(null,arguments)};
b._jxlProcessInput=function(){return(b._jxlProcessInput=b.asm.B).apply(null,arguments)};var $a=b._malloc=function(){return($a=b._malloc=b.asm.C).apply(null,arguments)};b._jxlFlush=function(){return(b._jxlFlush=b.asm.D).apply(null,arguments)};b._jxlDecompress=function(){return(b._jxlDecompress=b.asm.F).apply(null,arguments)};b._jxlCleanup=function(){return(b._jxlCleanup=b.asm.G).apply(null,arguments)};b.__emscripten_tls_init=function(){return(b.__emscripten_tls_init=b.asm.H).apply(null,arguments)};
var S=b._pthread_self=function(){return(S=b._pthread_self=b.asm.I).apply(null,arguments)},ab=b.__emscripten_thread_init=function(){return(ab=b.__emscripten_thread_init=b.asm.J).apply(null,arguments)};b.__emscripten_thread_crashed=function(){return(b.__emscripten_thread_crashed=b.asm.K).apply(null,arguments)};
var Ta=b._emscripten_run_in_main_runtime_thread_js=function(){return(Ta=b._emscripten_run_in_main_runtime_thread_js=b.asm.L).apply(null,arguments)},Oa=b.__emscripten_proxy_execute_task_queue=function(){return(Oa=b.__emscripten_proxy_execute_task_queue=b.asm.M).apply(null,arguments)},Fa=b.__emscripten_thread_free_data=function(){return(Fa=b.__emscripten_thread_free_data=b.asm.N).apply(null,arguments)},Ja=b.__emscripten_thread_exit=function(){return(Ja=b.__emscripten_thread_exit=b.asm.O).apply(null,
arguments)},eb=b._setThrew=function(){return(eb=b._setThrew=b.asm.P).apply(null,arguments)},Ha=b._emscripten_stack_set_limits=function(){return(Ha=b._emscripten_stack_set_limits=b.asm.Q).apply(null,arguments)},Y=b.stackSave=function(){return(Y=b.stackSave=b.asm.R).apply(null,arguments)},U=b.stackRestore=function(){return(U=b.stackRestore=b.asm.S).apply(null,arguments)},Ra=b.stackAlloc=function(){return(Ra=b.stackAlloc=b.asm.T).apply(null,arguments)};
b.___cxa_is_pointer_type=function(){return(b.___cxa_is_pointer_type=b.asm.U).apply(null,arguments)};function bb(a,c,d){var e=Y();try{return Ia(a)(c,d)}catch(g){U(e);if(g!==g+0)throw g;eb(1,0)}}function cb(a,c,d){var e=Y();try{Ia(a)(c,d)}catch(g){U(e);if(g!==g+0)throw g;eb(1,0)}}b.keepRuntimeAlive=function(){return noExitRuntime};b.wasmMemory=G;b.ExitStatus=C;b.PThread=Q;var Z;O=function fb(){Z||gb();Z||(O=fb)};
function gb(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!ia)){u||T(sa);f(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(!u){if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();ta.unshift(c)}T(ta)}}}if(!(0<N))if(u)f(b),u||T(sa),postMessage({cmd:"loaded"});else{if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ua();T(ra);0<N||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},
1);a()},1)):a())}}if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();gb();


  return JxlDecoderModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JxlDecoderModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JxlDecoderModule; });
else if (typeof exports === 'object')
  exports["JxlDecoderModule"] = JxlDecoderModule;
