
var JxlCodecModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JxlCodecModule) {
  JxlCodecModule = JxlCodecModule || {};


var c;c||(c=typeof JxlCodecModule !== 'undefined' ? JxlCodecModule : {});var g,l;c.ready=new Promise(function(a,b){g=a;l=b});var aa=Object.assign({},c),m=(a,b)=>{throw b;},q="object"===typeof window,r="function"===typeof importScripts,t="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u=c.ENVIRONMENT_IS_PTHREAD||!1,w="";function ba(a){return c.locateFile?c.locateFile(a,w):w+a}var x,y,z,fs,A,B;
if(t){w=r?require("path").dirname(w)+"/":__dirname+"/";B=()=>{A||(fs=require("fs"),A=require("path"))};x=function(b,d){B();b=A.normalize(b);return fs.readFileSync(b,d?void 0:"utf8")};z=b=>{b=x(b,!0);b.buffer||(b=new Uint8Array(b));return b};y=(b,d,e)=>{B();b=A.normalize(b);fs.readFile(b,function(f,h){f?e(f):d(h.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof C))throw b;});process.on("unhandledRejection",
function(b){throw b;});m=(b,d)=>{if(D())throw process.exitCode=b,d;d instanceof C||E("exiting due to exception: "+d);process.exit(b)};c.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(q||r)r?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),
_scriptDir&&(w=_scriptDir),0!==w.indexOf("blob:")?w=w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1):w="",t||(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),y=(a,b,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;
e.send(null)});t&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ca=console.log.bind(console),da=console.warn.bind(console);t&&(B(),ca=a=>fs.writeSync(1,a+"\n"),da=a=>fs.writeSync(2,a+"\n"));var ea=c.print||ca,E=c.printErr||da;Object.assign(c,aa);aa=null;c.quit&&(m=c.quit);var F,G;c.wasmBinary&&(G=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!0;"object"!==typeof WebAssembly&&I("no native wasm support detected");var J,fa,K=!1;
function ha(a){var b=new TextDecoder(a);this.decode=d=>{d.buffer instanceof SharedArrayBuffer&&(d=new Uint8Array(d));return b.decode.call(b,d)}}var ia="undefined"!==typeof TextDecoder?new ha("utf8"):void 0;
function L(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&ia)return ia.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}"undefined"!==typeof TextDecoder&&new ha("utf-16le");
var M,N,O,P;u&&(M=c.buffer);var ja=c.INITIAL_MEMORY||78643200;
if(u)J=c.wasmMemory,M=c.buffer;else if(c.wasmMemory)J=c.wasmMemory;else if(J=new WebAssembly.Memory({initial:ja/65536,maximum:ja/65536,shared:!0}),!(J.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),t&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
J&&(M=J.buffer);ja=M.byteLength;var Q=M;M=Q;c.HEAP8=new Int8Array(Q);c.HEAP16=new Int16Array(Q);c.HEAP32=O=new Int32Array(Q);c.HEAPU8=N=new Uint8Array(Q);c.HEAPU16=new Uint16Array(Q);c.HEAPU32=new Uint32Array(Q);c.HEAPF32=new Float32Array(Q);c.HEAPF64=P=new Float64Array(Q);var ka,la=[],ma=[],na=[],oa=0;function D(){return noExitRuntime||0<oa}function pa(){var a=c.preRun.shift();la.unshift(a)}var R=0,qa=null,S=null;c.preloadedImages={};c.preloadedAudios={};
function I(a){if(u)postMessage({cmd:"onAbort",arg:a});else if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";E(a);K=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");l(a);throw a;}function ra(){return T.startsWith("data:application/octet-stream;base64,")}var T;T="jxl_emcc.wasm";ra()||(T=ba(T));function sa(){var a=T;try{if(a==T&&G)return new Uint8Array(G);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}catch(b){I(b)}}
function ta(){if(!G&&(q||r)){if("function"===typeof fetch&&!T.startsWith("file://"))return fetch(T,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+T+"'";return a.arrayBuffer()}).catch(function(){return sa()});if(y)return new Promise(function(a,b){y(T,function(d){a(new Uint8Array(d))},b)})}return Promise.resolve().then(function(){return sa()})}var ua={};
function U(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(c);else{var d=b.Ba;"number"===typeof d?void 0===b.U?va(d)():va(d)(b.U):d(void 0===b.U?null:b.U)}}}function wa(a){var b=xa();a=a();ya(b);return a}function za(a){var b=V.R[a];b&&(O[a>>2]=0,V.ia(b.worker))}
var V={S:[],W:[],ba:[],oa:function(){u?V.ra():V.qa()},qa:function(){for(var a=0;4>a;++a)V.da()},ra:function(){V.receiveObjectTransfer=V.ta;V.threadInit=V.ka;V.setExitStatus=V.va;noExitRuntime=!1},R:{},va:function(){},ja:function(){for(var a in V.R){var b=V.R[a];b&&b.worker&&V.ia(b.worker)}for(a=0;a<V.S.length;++a)V.S[a].terminate();V.S=[]},ia:function(a){V.ua(function(){delete V.R[a.T.aa];V.S.push(a);V.W.splice(V.W.indexOf(a),1);Aa(a.T.aa);a.T=void 0})},ua:function(a){O[Ba>>2]=0;try{a()}finally{O[Ba>>
2]=1}},ta:function(){},ka:function(){for(var a in V.ba)V.ba[a]()},ga:function(a,b){a.onmessage=d=>{d=d.data;var e=d.cmd;a.T&&(V.la=a.T.aa);if(d.targetThread&&d.targetThread!=W()){var f=V.R[d.Ha];f?f.worker.postMessage(d,d.transferList):E('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Ca();else if("spawnThread"===e)Da(d);else if("cleanupThread"===e)za(d.thread);else if("killThread"===
e)d=d.thread,O[d>>2]=0,e=V.R[d],delete V.R[d],e.worker.terminate(),Aa(d),V.W.splice(V.W.indexOf(e.worker),1),e.worker.T=void 0;else if("cancelThread"===e)V.R[d.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===e)a.loaded=!0,b&&b(a),a.V&&(a.V(),delete a.V);else if("print"===e)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===e)E("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("setimmediate"===d.target)a.postMessage(d);else if("onAbort"===
e){if(c.onAbort)c.onAbort(d.arg)}else E("worker sent an unknown command "+e);V.la=void 0};a.onerror=d=>{E("worker sent an error! "+d.filename+":"+d.lineno+": "+d.message);throw d;};t&&(a.on("message",function(d){a.onmessage({data:d})}),a.on("error",function(d){a.onerror(d)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:c.mainScriptUrlOrBlob||_scriptDir,wasmMemory:J,wasmModule:fa})},da:function(){var a=ba("jxl_emcc.worker.js");V.S.push(new Worker(a))},na:function(){0==V.S.length&&
(V.da(),V.ga(V.S[0]));return V.S.pop()}};c.establishStackSpace=function(){var a=W(),b=O[a+44>>2];Ea(b,b-O[a+48>>2]);ya(b)};function Fa(a){if(u)return X(1,0,a);try{Ga(a)}catch(b){b instanceof C||"unwind"==b||m(1,b)}}var Y=[];function va(a){var b=Y[a];b||(a>=Y.length&&(Y.length=a+1),Y[a]=b=ka.get(a));return b}c.invokeEntryPoint=function(a,b){return va(a)(b)};var Ha;Ha=t?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?()=>performance.now()-c.__performance_now_clock_drift:()=>performance.now();
function Da(a){var b=V.na();if(!b)return 6;V.W.push(b);var d=V.R[a.$]={worker:b,aa:a.$};b.T=d;var e={cmd:"run",start_routine:a.wa,arg:a.U,threadInfoStruct:a.$};b.V=()=>{e.time=performance.now();b.postMessage(e,a.xa)};b.loaded&&(b.V(),delete b.V);return 0}function X(a,b){var d=arguments.length-2,e=arguments;return wa(function(){for(var f=Ia(8*d),h=f>>3,k=0;k<d;k++)P[h+k]=e[2+k];return Ja(a,d,f,b)})}var Ka=[];
function La(a,b,d,e){wa(function(){var f=Ia(12),h=0;if(b){for(var k=h=0;k<b.length;++k){var n=b.charCodeAt(k);55296<=n&&57343>=n&&(n=65536+((n&1023)<<10)|b.charCodeAt(++k)&1023);127>=n?++h:h=2047>=n?h+2:65535>=n?h+3:h+4}n=h+1;k=h=Ma(n);if(0<n){n=k+n-1;for(var v=0;v<b.length;++v){var p=b.charCodeAt(v);if(55296<=p&&57343>=p){var H=b.charCodeAt(++v);p=65536+((p&1023)<<10)|H&1023}if(127>=p){if(k>=n)break;N[k++]=p}else{if(2047>=p){if(k+1>=n)break;N[k++]=192|p>>6}else{if(65535>=p){if(k+2>=n)break;N[k++]=
224|p>>12}else{if(k+3>=n)break;N[k++]=240|p>>18;N[k++]=128|p>>12&63}N[k++]=128|p>>6&63}N[k++]=128|p&63}}N[k]=0}}O[f>>2]=h;O[f+4>>2]=d;O[f+8>>2]=e;Na(a,657457152,0,h,f)})}var Oa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Pa(a){a=2<a?a?L(N,a,void 0):"":a;return Oa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Qa(a,b,d){var e=Pa(a);if(!e)return-4;e.Z&&(O[e.Z>>2]=b,O[e.Z+4>>2]=d);if(e.ha||!e.za)e.ha&&(e=e.ha),a=!1,e.Y&&e.Y.X&&(a=e.Y.X.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=d,a&&e.Y.X.viewport(0,0,b,d);else return e.Z?(e=O[e.Z+8>>2],a=a?a?L(N,a,void 0):"":"",La(e,a,b,d),1):-4;return 0}function Ra(a,b,d){return u?X(2,1,a,b,d):Qa(a,b,d)}
function Sa(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(d,e){b.vertexAttribDivisorANGLE(d,e)},a.drawArraysInstanced=function(d,e,f,h){b.drawArraysInstancedANGLE(d,e,f,h)},a.drawElementsInstanced=function(d,e,f,h,k){b.drawElementsInstancedANGLE(d,e,f,h,k)})}
function Ta(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(d){b.deleteVertexArrayOES(d)},a.bindVertexArray=function(d){b.bindVertexArrayOES(d)},a.isVertexArray=function(d){return b.isVertexArrayOES(d)})}function Ua(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(d,e){b.drawBuffersWEBGL(d,e)})}
function Va(a,b){a.fa||(a.fa=a.getContext,a.getContext=function(e,f){f=a.fa(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var d=a.getContext("webgl",b);return d?Wa(d,b):0}function Wa(a,b){var d=Ma(8);O[d+4>>2]=W();var e={Ca:d,attributes:b,version:b.sa,X:a};a.canvas&&(a.canvas.Y=e);("undefined"===typeof b.ea||b.ea)&&Xa(e);return d}
function Xa(a){a||(a=Ya);if(!a.pa){a.pa=!0;var b=a.X;Sa(b);Ta(b);Ua(b);b.Aa=b.getExtension("EXT_disjoint_timer_query");b.Ea=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(d){d.includes("lose_context")||d.includes("debug")||b.getExtension(d)})}}var Ya,Za=["default","low-power","high-performance"],$a=[null,[],[]];function ab(a){return u?X(3,1,a):0}function bb(a,b,d,e,f){if(u)return X(4,1,a,b,d,e,f)}
function cb(a,b,d,e){if(u)return X(5,1,a,b,d,e);for(var f=0,h=0;h<d;h++){var k=O[b>>2],n=O[b+4>>2];b+=8;for(var v=0;v<n;v++){var p=N[k+v],H=$a[a];0===p||10===p?((1===a?ea:E)(L(H,0)),H.length=0):H.push(p)}f+=n}O[e>>2]=f;return 0}V.oa();
var db=[null,Fa,Ra,ab,bb,cb],gb={i:function(a){eb(a,!r,1,!q);V.ka()},g:function(a){u?postMessage({cmd:"cleanupThread",thread:a}):za(a)},d:function(a,b,d,e){if("undefined"===typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(u&&0===f.length)return fb(687865856,a,b,d,e);a={wa:d,$:a,U:e,xa:f};return u?(a.ya="spawnThread",postMessage(a,f),0):Da(a)},h:function(){return 2097152},m:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(u)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=V.R[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){I("")},e:function(){t||r||(F||(F={}),F["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(F["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,E("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},
c:Ha,q:function(a,b,d){N.copyWithin(a,b,b+d)},j:function(a,b,d){Ka.length=b;d>>=3;for(var e=0;e<b;e++)Ka[e]=P[d+e];return(0>a?ua[-a-1]:db[a]).apply(null,Ka)},o:function(){I("OOM")},k:function(a,b,d){return Pa(a)?Qa(a,b,d):Ra(a,b,d)},s:function(){throw"unwind";},l:function(a,b){b>>=2;b={alpha:!!O[b],depth:!!O[b+1],stencil:!!O[b+2],antialias:!!O[b+3],premultipliedAlpha:!!O[b+4],preserveDrawingBuffer:!!O[b+5],powerPreference:Za[O[b+6]],failIfMajorPerformanceCaveat:!!O[b+7],sa:O[b+8],Da:O[b+9],ea:O[b+
10],ma:O[b+11],Fa:O[b+12],Ga:O[b+13]};a=Pa(a);return!a||b.ma?0:Va(a,b)},r:function(a){Ga(a)},p:ab,n:bb,f:cb,a:J||c.wasmMemory};
(function(){function a(f,h){c.asm=f.exports;V.ba.push(c.asm.B);ka=c.asm.A;ma.unshift(c.asm.t);fa=h;if(!u){var k=V.S.length;V.S.forEach(function(n){V.ga(n,function(){if(!--k&&(R--,c.monitorRunDependencies&&c.monitorRunDependencies(R),0==R&&(null!==qa&&(clearInterval(qa),qa=null),S))){var v=S;S=null;v()}})})}}function b(f){a(f.instance,f.module)}function d(f){return ta().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(f,function(h){E("failed to asynchronously prepare wasm: "+
h);I(h)})}var e={a:gb};u||(R++,c.monitorRunDependencies&&c.monitorRunDependencies(R));if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return G||"function"!==typeof WebAssembly.instantiateStreaming||ra()||T.startsWith("file://")||"function"!==typeof fetch?d(b):fetch(T,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(h){E("wasm streaming compile failed: "+
h);E("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(l);return{}})();c.___wasm_call_ctors=function(){return(c.___wasm_call_ctors=c.asm.t).apply(null,arguments)};c._jxlCreateInstance=function(){return(c._jxlCreateInstance=c.asm.u).apply(null,arguments)};c._jxlDestroyInstance=function(){return(c._jxlDestroyInstance=c.asm.v).apply(null,arguments)};c._free=function(){return(c._free=c.asm.w).apply(null,arguments)};
c._jxlProcessInput=function(){return(c._jxlProcessInput=c.asm.x).apply(null,arguments)};var Ma=c._malloc=function(){return(Ma=c._malloc=c.asm.y).apply(null,arguments)};c._jxlFlush=function(){return(c._jxlFlush=c.asm.z).apply(null,arguments)};c._emscripten_tls_init=function(){return(c._emscripten_tls_init=c.asm.B).apply(null,arguments)};c.__emscripten_thread_crashed=function(){return(c.__emscripten_thread_crashed=c.asm.C).apply(null,arguments)};
var eb=c.__emscripten_thread_init=function(){return(eb=c.__emscripten_thread_init=c.asm.D).apply(null,arguments)},W=c._pthread_self=function(){return(W=c._pthread_self=c.asm.E).apply(null,arguments)},Ca=c._emscripten_main_thread_process_queued_calls=function(){return(Ca=c._emscripten_main_thread_process_queued_calls=c.asm.F).apply(null,arguments)};c._emscripten_current_thread_process_queued_calls=function(){return(c._emscripten_current_thread_process_queued_calls=c.asm.G).apply(null,arguments)};
var fb=c._emscripten_sync_run_in_main_thread_4=function(){return(fb=c._emscripten_sync_run_in_main_thread_4=c.asm.H).apply(null,arguments)},Ja=c._emscripten_run_in_main_runtime_thread_js=function(){return(Ja=c._emscripten_run_in_main_runtime_thread_js=c.asm.I).apply(null,arguments)},Na=c._emscripten_dispatch_to_thread_=function(){return(Na=c._emscripten_dispatch_to_thread_=c.asm.J).apply(null,arguments)},Aa=c.__emscripten_thread_free_data=function(){return(Aa=c.__emscripten_thread_free_data=c.asm.K).apply(null,
arguments)};c.__emscripten_thread_exit=function(){return(c.__emscripten_thread_exit=c.asm.L).apply(null,arguments)};
var Ea=c._emscripten_stack_set_limits=function(){return(Ea=c._emscripten_stack_set_limits=c.asm.M).apply(null,arguments)},xa=c.stackSave=function(){return(xa=c.stackSave=c.asm.N).apply(null,arguments)},ya=c.stackRestore=function(){return(ya=c.stackRestore=c.asm.O).apply(null,arguments)},Ia=c.stackAlloc=function(){return(Ia=c.stackAlloc=c.asm.P).apply(null,arguments)},Ba=c.__emscripten_allow_main_runtime_queued_calls=165808;c.keepRuntimeAlive=D;c.PThread=V;c.PThread=V;c.wasmMemory=J;c.ExitStatus=C;
var Z;function C(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}S=function hb(){Z||ib();Z||(S=hb)};
function ib(){function a(){if(!Z&&(Z=!0,c.calledRun=!0,!K)){u||U(ma);g(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(!u){if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();na.unshift(b)}U(na)}}}if(!(0<R))if(u)g(c),u||U(ma),postMessage({cmd:"loaded"});else{if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)pa();U(la);0<R||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}c.run=ib;function Ga(a){if(u)throw Fa(a),"unwind";D()||u||V.ja();if(!D()){V.ja();if(c.onExit)c.onExit(a);K=!0}m(a,new C(a))}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();ib();


  return JxlCodecModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JxlCodecModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JxlCodecModule; });
else if (typeof exports === 'object')
  exports["JxlCodecModule"] = JxlCodecModule;
