
var JxlCodecModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JxlCodecModule) {
  JxlCodecModule = JxlCodecModule || {};


var f;f||(f=typeof JxlCodecModule !== 'undefined' ? JxlCodecModule : {});var aa,m;f.ready=new Promise(function(a,b){aa=a;m=b});var ba=Object.assign({},f),r="./this.program",ca="object"===typeof window,t="function"===typeof importScripts,da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,u="",w,x,y,fs,z,B;
if(da)u=t?require("path").dirname(u)+"/":__dirname+"/",B=()=>{z||(fs=require("fs"),z=require("path"))},w=function(a,b){B();a=z.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},y=a=>{a=w(a,!0);a.buffer||(a=new Uint8Array(a));return a},x=(a,b,d)=>{B();a=z.normalize(a);fs.readFile(a,function(e,g){e?d(e):b(g.buffer)})},1<process.argv.length&&(r=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;
}),f.inspect=function(){return"[Emscripten Module object]"};else if(ca||t)t?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):u="",w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
x=(a,b,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)};var ea=f.print||console.log.bind(console),C=f.printErr||console.warn.bind(console);Object.assign(f,ba);ba=null;f.thisProgram&&(r=f.thisProgram);var fa=0,E;f.wasmBinary&&(E=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&F("no native wasm support detected");
var G,ha=!1,ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&ia)return ia.decode(a.subarray(b,d));for(e="";b<d;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}function H(a){return a?ja(I,a,void 0):""}var ka,J,I,K;
function la(){var a=G.buffer;ka=a;f.HEAP8=J=new Int8Array(a);f.HEAP16=new Int16Array(a);f.HEAP32=K=new Int32Array(a);f.HEAPU8=I=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a)}var ma,na=[],oa=[],pa=[];function qa(){var a=f.preRun.shift();na.unshift(a)}var L=0,M=null,N=null;f.preloadedImages={};f.preloadedAudios={};
function F(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";C(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");m(a);throw a;}function ra(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="jxl_emcc.wasm";if(!ra()){var sa=O;O=f.locateFile?f.locateFile(sa,u):u+sa}function ta(){var a=O;try{if(a==O&&E)return new Uint8Array(E);if(y)return y(a);throw"both async and sync fetching of the wasm failed";}catch(b){F(b)}}
function ua(){if(!E&&(ca||t)){if("function"===typeof fetch&&!O.startsWith("file://"))return fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return ta()});if(x)return new Promise(function(a,b){x(O,function(d){a(new Uint8Array(d))},b)})}return Promise.resolve().then(function(){return ta()})}
function P(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var d=b.ka;"number"===typeof d?void 0===b.Y?Q(d)():Q(d)(b.Y):d(void 0===b.Y?null:b.Y)}}}var R=[];function Q(a){var b=R[a];b||(a>=R.length&&(R.length=a+1),R[a]=b=ma.get(a));return b}
function va(a){this.T=a-16;this.ea=function(b){K[this.T+4>>2]=b};this.aa=function(b){K[this.T+8>>2]=b};this.ba=function(){K[this.T>>2]=0};this.$=function(){J[this.T+12>>0]=0};this.da=function(){J[this.T+13>>0]=0};this.Z=function(b,d){this.ea(b);this.aa(d);this.ba();this.$();this.da()}}var wa=0,xa=[null,[],[]],Ba={},Ca={};
function Da(){if(!Ea){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:r||"./this.program"},b;for(b in Ca)void 0===Ca[b]?delete a[b]:a[b]=Ca[b];var d=[];for(b in a)d.push(b+"="+a[b]);Ea=d}return Ea}var Ea;function S(a){return 0===a%4&&(0!==a%100||0===a%400)}function Fa(a,b){for(var d=0,e=0;e<=b;d+=a[e++]);return d}
var T=[31,29,31,30,31,30,31,31,30,31,30,31],U=[31,28,31,30,31,30,31,31,30,31,30,31];function V(a,b){for(a=new Date(a.getTime());0<b;){var d=a.getMonth(),e=(S(a.getFullYear())?T:U)[d];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ga(a,b,d,e){function g(c,k,n){for(c="number"===typeof c?c.toString():c||"";c.length<k;)c=n[0]+c;return c}function h(c,k){return g(c,k,"0")}function l(c,k){function n(ya){return 0>ya?-1:0<ya?1:0}var A;0===(A=n(c.getFullYear()-k.getFullYear()))&&0===(A=n(c.getMonth()-k.getMonth()))&&(A=n(c.getDate()-k.getDate()));return A}function p(c){switch(c.getDay()){case 0:return new Date(c.getFullYear()-1,11,29);case 1:return c;case 2:return new Date(c.getFullYear(),0,3);case 3:return new Date(c.getFullYear(),
0,2);case 4:return new Date(c.getFullYear(),0,1);case 5:return new Date(c.getFullYear()-1,11,31);case 6:return new Date(c.getFullYear()-1,11,30)}}function D(c){c=V(new Date(c.R+1900,0,1),c.X);var k=new Date(c.getFullYear()+1,0,4),n=p(new Date(c.getFullYear(),0,4));k=p(k);return 0>=l(n,c)?0>=l(k,c)?c.getFullYear()+1:c.getFullYear():c.getFullYear()-1}var v=K[e+40>>2];e={ha:K[e>>2],ga:K[e+4>>2],V:K[e+8>>2],U:K[e+12>>2],S:K[e+16>>2],R:K[e+20>>2],W:K[e+24>>2],X:K[e+28>>2],oa:K[e+32>>2],fa:K[e+36>>2],ia:v?
H(v):""};d=H(d);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in v)d=d.replace(new RegExp(q,"g"),v[q]);var za="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Aa="January February March April May June July August September October November December".split(" ");v={"%a":function(c){return za[c.W].substring(0,3)},"%A":function(c){return za[c.W]},"%b":function(c){return Aa[c.S].substring(0,3)},"%B":function(c){return Aa[c.S]},"%C":function(c){return h((c.R+1900)/100|0,2)},"%d":function(c){return h(c.U,2)},"%e":function(c){return g(c.U,2," ")},"%g":function(c){return D(c).toString().substring(2)},"%G":function(c){return D(c)},"%H":function(c){return h(c.V,2)},
"%I":function(c){c=c.V;0==c?c=12:12<c&&(c-=12);return h(c,2)},"%j":function(c){return h(c.U+Fa(S(c.R+1900)?T:U,c.S-1),3)},"%m":function(c){return h(c.S+1,2)},"%M":function(c){return h(c.ga,2)},"%n":function(){return"\n"},"%p":function(c){return 0<=c.V&&12>c.V?"AM":"PM"},"%S":function(c){return h(c.ha,2)},"%t":function(){return"\t"},"%u":function(c){return c.W||7},"%U":function(c){var k=new Date(c.R+1900,0,1),n=0===k.getDay()?k:V(k,7-k.getDay());c=new Date(c.R+1900,c.S,c.U);return 0>l(n,c)?h(Math.ceil((31-
n.getDate()+(Fa(S(c.getFullYear())?T:U,c.getMonth()-1)-31)+c.getDate())/7),2):0===l(n,k)?"01":"00"},"%V":function(c){var k=new Date(c.R+1901,0,4),n=p(new Date(c.R+1900,0,4));k=p(k);var A=V(new Date(c.R+1900,0,1),c.X);return 0>l(A,n)?"53":0>=l(k,A)?"01":h(Math.ceil((n.getFullYear()<c.R+1900?c.X+32-n.getDate():c.X+1-n.getDate())/7),2)},"%w":function(c){return c.W},"%W":function(c){var k=new Date(c.R,0,1),n=1===k.getDay()?k:V(k,0===k.getDay()?1:7-k.getDay()+1);c=new Date(c.R+1900,c.S,c.U);return 0>l(n,
c)?h(Math.ceil((31-n.getDate()+(Fa(S(c.getFullYear())?T:U,c.getMonth()-1)-31)+c.getDate())/7),2):0===l(n,k)?"01":"00"},"%y":function(c){return(c.R+1900).toString().substring(2)},"%Y":function(c){return c.R+1900},"%z":function(c){c=c.fa;var k=0<=c;c=Math.abs(c)/60;return(k?"+":"-")+String("0000"+(c/60*100+c%60)).slice(-4)},"%Z":function(c){return c.ia},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(q in v)d.includes(q)&&(d=d.replace(new RegExp(q,"g"),v[q](e)));d=d.replace(/\0\0/g,"%");
q=Ha(d);if(q.length>b)return 0;J.set(q,a);return q.length-1}
function Ha(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}b=Array(b+1);e=b.length;d=0;if(0<e){e=d+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(d>=e)break;b[d++]=h}else{if(2047>=h){if(d+1>=e)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;b[d++]=224|h>>12}else{if(d+3>=e)break;
b[d++]=240|h>>18;b[d++]=128|h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0}return b}
var Va={E:function(a){return Ia(a+16)+16},D:function(a,b,d){(new va(a)).Z(b,d);wa++;throw a;},m:function(){return 0},x:function(){return 0},y:function(){},v:function(){},t:function(){throw"longjmp";},a:function(){F("")},z:function(a,b,d){I.copyWithin(a,b,b+d)},u:function(a){var b=I.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{G.grow(Math.min(2147483648,e)-ka.byteLength+65535>>>16);la();
var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},r:function(a,b){var d=0;Da().forEach(function(e,g){var h=b+d;g=K[a+4*g>>2]=h;for(h=0;h<e.length;++h)J[g++>>0]=e.charCodeAt(h);J[g>>0]=0;d+=e.length+1});return 0},s:function(a,b){var d=Da();K[a>>2]=d.length;var e=0;d.forEach(function(g){e+=g.length+1});K[b>>2]=e;return 0},k:function(){return 0},w:function(a,b,d,e){a=Ba.la(a);b=Ba.ja(a,b,d);K[e>>2]=b;return 0},o:function(){},l:function(a,b,d,e){for(var g=0,h=0;h<d;h++){var l=K[b>>2],p=K[b+4>>
2];b+=8;for(var D=0;D<p;D++){var v=I[l+D],q=xa[a];0===v||10===v?((1===a?ea:C)(ja(q,0)),q.length=0):q.push(v)}g+=p}K[e>>2]=g;return 0},b:function(){return fa},n:Ja,f:Ka,g:La,h:Ma,j:Na,i:Oa,A:Pa,d:Qa,C:Ra,e:Sa,B:Ta,c:function(a){fa=a},q:function(a,b,d,e){return Ga(a,b,d,e)},p:function(a){if(da){if(!a)return 1;a=H(a);if(!a.length)return 0;a=require("child_process").na(a,[],{ma:!0,stdio:"inherit"});var b=(d,e)=>d<<8|e;return null===a.status?b(0,(d=>{switch(d){case "SIGHUP":return 1;case "SIGQUIT":return 3;
case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):a.status<<8|0}if(!a)return 0;K[Ua()>>2]=52;return-1}};
(function(){function a(g){f.asm=g.exports;G=f.asm.F;la();ma=f.asm.K;oa.unshift(f.asm.G);L--;f.monitorRunDependencies&&f.monitorRunDependencies(L);0==L&&(null!==M&&(clearInterval(M),M=null),N&&(g=N,N=null,g()))}function b(g){a(g.instance)}function d(g){return ua().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(g,function(h){C("failed to asynchronously prepare wasm: "+h);F(h)})}var e={a:Va};L++;f.monitorRunDependencies&&f.monitorRunDependencies(L);if(f.instantiateWasm)try{return f.instantiateWasm(e,
a)}catch(g){return C("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return E||"function"!==typeof WebAssembly.instantiateStreaming||ra()||O.startsWith("file://")||"function"!==typeof fetch?d(b):fetch(O,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(h){C("wasm streaming compile failed: "+h);C("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(m);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.G).apply(null,arguments)};f._jxlCompress=function(){return(f._jxlCompress=f.asm.H).apply(null,arguments)};var Ia=f._malloc=function(){return(Ia=f._malloc=f.asm.I).apply(null,arguments)};f._jxlDecompress=function(){return(f._jxlDecompress=f.asm.J).apply(null,arguments)};f._free=function(){return(f._free=f.asm.L).apply(null,arguments)};
var Ua=f.___errno_location=function(){return(Ua=f.___errno_location=f.asm.M).apply(null,arguments)},W=f._setThrew=function(){return(W=f._setThrew=f.asm.N).apply(null,arguments)},X=f.stackSave=function(){return(X=f.stackSave=f.asm.O).apply(null,arguments)},Y=f.stackRestore=function(){return(Y=f.stackRestore=f.asm.P).apply(null,arguments)};function Na(a,b,d,e,g){var h=X();try{return Q(a)(b,d,e,g)}catch(l){Y(h);if(l!==l+0&&"longjmp"!==l)throw l;W(1,0)}}
function Ka(a,b){var d=X();try{return Q(a)(b)}catch(e){Y(d);if(e!==e+0&&"longjmp"!==e)throw e;W(1,0)}}function Ma(a,b,d,e){var g=X();try{return Q(a)(b,d,e)}catch(h){Y(g);if(h!==h+0&&"longjmp"!==h)throw h;W(1,0)}}function Sa(a,b,d,e,g){var h=X();try{Q(a)(b,d,e,g)}catch(l){Y(h);if(l!==l+0&&"longjmp"!==l)throw l;W(1,0)}}function Ra(a,b,d,e){var g=X();try{Q(a)(b,d,e)}catch(h){Y(g);if(h!==h+0&&"longjmp"!==h)throw h;W(1,0)}}
function Ta(a,b,d,e,g,h){var l=X();try{Q(a)(b,d,e,g,h)}catch(p){Y(l);if(p!==p+0&&"longjmp"!==p)throw p;W(1,0)}}function La(a,b,d){var e=X();try{return Q(a)(b,d)}catch(g){Y(e);if(g!==g+0&&"longjmp"!==g)throw g;W(1,0)}}function Qa(a,b,d){var e=X();try{Q(a)(b,d)}catch(g){Y(e);if(g!==g+0&&"longjmp"!==g)throw g;W(1,0)}}function Ja(a){var b=X();try{return Q(a)()}catch(d){Y(b);if(d!==d+0&&"longjmp"!==d)throw d;W(1,0)}}
function Pa(a){var b=X();try{Q(a)()}catch(d){Y(b);if(d!==d+0&&"longjmp"!==d)throw d;W(1,0)}}function Oa(a,b,d,e,g,h){var l=X();try{return Q(a)(b,d,e,g,h)}catch(p){Y(l);if(p!==p+0&&"longjmp"!==p)throw p;W(1,0)}}var Z;N=function Wa(){Z||Xa();Z||(N=Wa)};
function Xa(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!ha)){P(oa);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();pa.unshift(b)}P(pa)}}if(!(0<L)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)qa();P(na);0<L||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=Xa;
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Xa();


  return JxlCodecModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JxlCodecModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JxlCodecModule; });
else if (typeof exports === 'object')
  exports["JxlCodecModule"] = JxlCodecModule;
