
var JxlCodecModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JxlCodecModule) {
  JxlCodecModule = JxlCodecModule || {};


var b;b||(b=typeof JxlCodecModule !== 'undefined' ? JxlCodecModule : {});var f,h;b.ready=new Promise(function(a,c){f=a;h=c});var aa=Object.assign({},b),l=(a,c)=>{throw c;},n="object"==typeof window,p="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,u=b.ENVIRONMENT_IS_PTHREAD||!1,v="";function ba(a){return b.locateFile?b.locateFile(a,v):v+a}var x,y,z;
if(r){v=p?require("path").dirname(v)+"/":__dirname+"/";var fs,C;"function"===typeof require&&(fs=require("fs"),C=require("path"));x=(c,d)=>{c=C.normalize(c);return fs.readFileSync(c,d?void 0:"utf8")};z=c=>{c=x(c,!0);c.buffer||(c=new Uint8Array(c));return c};y=(c,d,e)=>{c=C.normalize(c);fs.readFile(c,function(g,k){g?e(g):d(k.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof D))throw c;});process.on("unhandledRejection",
function(c){throw c;});l=(c,d)=>{if(noExitRuntime)throw process.exitCode=c,d;d instanceof D||E("exiting due to exception: "+d);process.exit(c)};b.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(c){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),c;}global.Worker=a.Worker}else if(n||p)p?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),
_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",r||(x=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},p&&(z=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),y=(a,c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;
e.send(null)});r&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var ca=console.log.bind(console),da=console.warn.bind(console);r&&(ca=a=>fs.writeSync(1,a+"\n"),da=a=>fs.writeSync(2,a+"\n"));var ea=b.print||ca,E=b.printErr||da;Object.assign(b,aa);aa=null;b.quit&&(l=b.quit);var F;b.wasmBinary&&(F=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!=typeof WebAssembly&&G("no native wasm support detected");
var H,fa,I=!1,ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L,ia,ja,M,N,ka;u&&(L=b.buffer);var na=b.INITIAL_MEMORY||78643200;
if(u)H=b.wasmMemory,L=b.buffer;else if(b.wasmMemory)H=b.wasmMemory;else if(H=new WebAssembly.Memory({initial:na/65536,maximum:na/65536,shared:!0}),!(H.buffer instanceof SharedArrayBuffer))throw E("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),r&&E("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");H&&(L=H.buffer);na=L.byteLength;var O=L;L=O;b.HEAP8=ia=new Int8Array(O);b.HEAP16=new Int16Array(O);b.HEAP32=M=new Int32Array(O);b.HEAPU8=ja=new Uint8Array(O);b.HEAPU16=new Uint16Array(O);b.HEAPU32=N=new Uint32Array(O);b.HEAPF32=new Float32Array(O);b.HEAPF64=ka=new Float64Array(O);var oa,pa=[],qa=[],ra=[];function sa(){var a=b.preRun.shift();pa.unshift(a)}var P=0,ta=null,Q=null;
function G(a){if(u)postMessage({cmd:"onAbort",arg:a});else if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";E(a);I=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");h(a);throw a;}function ua(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="jxl_emcc.wasm";ua()||(R=ba(R));function va(){var a=R;try{if(a==R&&F)return new Uint8Array(F);if(z)return z(a);throw"both async and sync fetching of the wasm failed";}catch(c){G(c)}}
function wa(){if(!F&&(n||p)){if("function"==typeof fetch&&!R.startsWith("file://"))return fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return va()});if(y)return new Promise(function(a,c){y(R,function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return va()})}var xa={};
function D(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function ya(a){(a=S.R[a])||G();S.Z(a)}function za(a){var c=S.la();if(!c)return 6;S.V.push(c);S.R[a.P]=c;c.P=a.P;var d={cmd:"run",start_routine:a.pa,arg:a.ja,pthread_ptr:a.P};c.U=()=>{d.time=performance.now();c.postMessage(d,a.ra)};c.loaded&&(c.U(),delete c.U);return 0}function Aa(a){if(u)return U(1,1,a);if(!noExitRuntime){S.qa();if(b.onExit)b.onExit(a);I=!0}l(a,new D(a))}
function Ba(a,c){if(!c&&u)throw Ca(a),"unwind";Aa(a)}
var S={S:[],V:[],ba:[],R:{},W:function(){u?S.na():S.ma()},ma:function(){for(var a=4;a--;)S.X()},na:function(){S.receiveObjectTransfer=S.oa;S.threadInitTLS=S.aa;S.setExitStatus=S.$;noExitRuntime=!1},$:function(){},qa:function(){for(var a of Object.values(S.R))S.Z(a);for(a of S.S)a.terminate();S.S=[]},Z:function(a){var c=a.P;delete S.R[c];S.S.push(a);S.V.splice(S.V.indexOf(a),1);a.P=0;Da(c)},oa:function(){},aa:function(){S.ba.forEach(a=>a())},Y:function(a,c){a.onmessage=d=>{d=d.data;var e=d.cmd;a.P&&
(S.ka=a.P);if(d.targetThread&&d.targetThread!=V()){var g=S.R[d.ta];g?g.postMessage(d,d.transferList):E('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===e)Ea(d.queue);else if("spawnThread"===e)za(d);else if("cleanupThread"===e)ya(d.thread);else if("killThread"===e)d=d.thread,e=S.R[d],delete S.R[d],e.terminate(),Da(d),S.V.splice(S.V.indexOf(e),1),e.P=0;else if("cancelThread"===e)S.R[d.thread].postMessage({cmd:"cancel"});
else if("loaded"===e)a.loaded=!0,c&&c(a),a.U&&(a.U(),delete a.U);else if("print"===e)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===e)E("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("setimmediate"===d.target)a.postMessage(d);else if("onAbort"===e){if(b.onAbort)b.onAbort(d.arg)}else e&&E("worker sent an unknown command "+e);S.ka=void 0};a.onerror=d=>{E("worker sent an error! "+d.filename+":"+d.lineno+": "+d.message);throw d;};r&&(a.on("message",
function(d){a.onmessage({data:d})}),a.on("error",function(d){a.onerror(d)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:b.mainScriptUrlOrBlob||_scriptDir,wasmMemory:H,wasmModule:fa})},X:function(){var a=ba("jxl_emcc.worker.js");S.S.push(new Worker(a))},la:function(){0==S.S.length&&(S.X(),S.Y(S.S[0]));return S.S.pop()}};b.PThread=S;function W(a){for(;0<a.length;)a.shift()(b)}b.establishStackSpace=function(){var a=V(),c=M[a+44>>2];Fa(c,c-M[a+48>>2]);Ga(c)};
function Ca(a){if(u)return U(2,0,a);try{Ba(a)}catch(c){c instanceof D||"unwind"==c||l(1,c)}}var X=[];b.invokeEntryPoint=function(a,c){var d=X[a];d||(a>=X.length&&(X.length=a+1),X[a]=d=oa.get(a));a=d(c);noExitRuntime?S.$(a):Ha(a)};
function Ia(a){this.T=a-24;this.ia=function(c){N[this.T+4>>2]=c};this.fa=function(c){N[this.T+8>>2]=c};this.ga=function(){M[this.T>>2]=0};this.ea=function(){ia[this.T+12>>0]=0};this.ha=function(){ia[this.T+13>>0]=0};this.W=function(c,d){this.da();this.ia(c);this.fa(d);this.ga();this.ea();this.ha()};this.da=function(){N[this.T+16>>2]=0}}var Ja=0;function Ka(a,c,d,e){return u?U(3,1,a,c,d,e):La(a,c,d,e)}
function La(a,c,d,e){if("undefined"==typeof SharedArrayBuffer)return E("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var g=[];if(u&&0===g.length)return Ka(a,c,d,e);a={pa:d,P:a,ja:e,ra:g};return u?(a.sa="spawnThread",postMessage(a,g),0):za(a)}function Ea(a){Atomics.store(M,a>>2,1);V()&&Ma(a);Atomics.compareExchange(M,a>>2,1,0)}b.executeNotifiedProxyingQueue=Ea;var Y,Na;
Na=r?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?()=>performance.now()-b.__performance_now_clock_drift:()=>performance.now();function Oa(a){var c=Pa();a=a();Ga(c);return a}function U(a,c){var d=arguments.length-2,e=arguments;return Oa(()=>{for(var g=Ra(8*d),k=g>>3,w=0;w<d;w++)ka[k+w]=e[2+w];return Sa(a,d,g,c)})}var Ta=[];function Ua(a){return u?U(4,1,a):52}function Va(a,c,d,e,g){return u?U(5,1,a,c,d,e,g):70}var Wa=[null,[],[]];
function Xa(a,c,d,e){if(u)return U(6,1,a,c,d,e);for(var g=0,k=0;k<d;k++){var w=N[c>>2],T=N[c+4>>2];c+=8;for(var J=0;J<T;J++){var K=ja[w+J],la=Wa[a];if(0===K||10===K){K=1===a?ea:E;var q=la;for(var t=0,A=t+NaN,B=t;q[B]&&!(B>=A);)++B;if(16<B-t&&q.buffer&&ha)q=ha.decode(q.buffer instanceof SharedArrayBuffer?q.slice(t,B):q.subarray(t,B));else{for(A="";t<B;){var m=q[t++];if(m&128){var ma=q[t++]&63;if(192==(m&224))A+=String.fromCharCode((m&31)<<6|ma);else{var Qa=q[t++]&63;m=224==(m&240)?(m&15)<<12|ma<<6|
Qa:(m&7)<<18|ma<<12|Qa<<6|q[t++]&63;65536>m?A+=String.fromCharCode(m):(m-=65536,A+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else A+=String.fromCharCode(m)}q=A}K(q);la.length=0}else la.push(K)}g+=T}N[e>>2]=g;return 0}S.W();
var Ya=[null,Aa,Ca,Ka,Ua,Va,Xa],ab={t:function(a){return Za(a+24)+24},s:function(a,c,d){(new Ia(a)).W(c,d);Ja++;throw a;},i:function(a){$a(a,!p,1,!n);S.aa()},e:function(a){u?postMessage({cmd:"cleanupThread",thread:a}):ya(a)},q:La,r:function(){return 2097152},g:function(a,c,d,e){if(a==c)setTimeout(()=>Ea(e));else if(u)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:e});else{a=S.R[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:e})}return 1},k:function(){return-1},b:function(){G("")},
f:function(){if(!r&&!p){var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";Y||(Y={});Y[a]||(Y[a]=1,r&&(a="warning: "+a),E(a))}},c:Na,h:function(a,c,d){ja.copyWithin(a,c,c+d)},j:function(a,c,d){Ta.length=c;d>>=3;for(var e=0;e<c;e++)Ta[e]=ka[d+e];return(0>a?xa[-a-1]:Ya[a]).apply(null,Ta)},n:function(){G("OOM")},l:function(){throw"unwind";},p:Ba,o:Ua,m:Va,d:Xa,a:H||b.wasmMemory};
(function(){function a(g,k){b.asm=g.exports;S.ba.push(b.asm.C);oa=b.asm.B;qa.unshift(b.asm.u);fa=k;if(!u){var w=S.S.length;S.S.forEach(function(T){S.Y(T,function(){if(!--w&&(P--,b.monitorRunDependencies&&b.monitorRunDependencies(P),0==P&&(null!==ta&&(clearInterval(ta),ta=null),Q))){var J=Q;Q=null;J()}})})}}function c(g){a(g.instance,g.module)}function d(g){return wa().then(function(k){return WebAssembly.instantiate(k,e)}).then(function(k){return k}).then(g,function(k){E("failed to asynchronously prepare wasm: "+
k);G(k)})}var e={a:ab};u||(P++,b.monitorRunDependencies&&b.monitorRunDependencies(P));if(b.instantiateWasm)try{return b.instantiateWasm(e,a)}catch(g){E("Module.instantiateWasm callback failed with error: "+g),h(g)}(function(){return F||"function"!=typeof WebAssembly.instantiateStreaming||ua()||R.startsWith("file://")||r||"function"!=typeof fetch?d(c):fetch(R,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(c,function(k){E("wasm streaming compile failed: "+
k);E("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(h);return{}})();b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.u).apply(null,arguments)};b._jxlCreateInstance=function(){return(b._jxlCreateInstance=b.asm.v).apply(null,arguments)};b._jxlDestroyInstance=function(){return(b._jxlDestroyInstance=b.asm.w).apply(null,arguments)};b._free=function(){return(b._free=b.asm.x).apply(null,arguments)};
b._jxlProcessInput=function(){return(b._jxlProcessInput=b.asm.y).apply(null,arguments)};var Za=b._malloc=function(){return(Za=b._malloc=b.asm.z).apply(null,arguments)};b._jxlFlush=function(){return(b._jxlFlush=b.asm.A).apply(null,arguments)};b.__emscripten_tls_init=function(){return(b.__emscripten_tls_init=b.asm.C).apply(null,arguments)};
var V=b._pthread_self=function(){return(V=b._pthread_self=b.asm.D).apply(null,arguments)},$a=b.__emscripten_thread_init=function(){return($a=b.__emscripten_thread_init=b.asm.E).apply(null,arguments)};b.__emscripten_thread_crashed=function(){return(b.__emscripten_thread_crashed=b.asm.F).apply(null,arguments)};
var Sa=b._emscripten_run_in_main_runtime_thread_js=function(){return(Sa=b._emscripten_run_in_main_runtime_thread_js=b.asm.G).apply(null,arguments)},Ma=b.__emscripten_proxy_execute_task_queue=function(){return(Ma=b.__emscripten_proxy_execute_task_queue=b.asm.H).apply(null,arguments)},Da=b.__emscripten_thread_free_data=function(){return(Da=b.__emscripten_thread_free_data=b.asm.I).apply(null,arguments)},Ha=b.__emscripten_thread_exit=function(){return(Ha=b.__emscripten_thread_exit=b.asm.J).apply(null,
arguments)},Fa=b._emscripten_stack_set_limits=function(){return(Fa=b._emscripten_stack_set_limits=b.asm.K).apply(null,arguments)},Pa=b.stackSave=function(){return(Pa=b.stackSave=b.asm.L).apply(null,arguments)},Ga=b.stackRestore=function(){return(Ga=b.stackRestore=b.asm.M).apply(null,arguments)},Ra=b.stackAlloc=function(){return(Ra=b.stackAlloc=b.asm.N).apply(null,arguments)};b.___cxa_is_pointer_type=function(){return(b.___cxa_is_pointer_type=b.asm.O).apply(null,arguments)};b.keepRuntimeAlive=function(){return noExitRuntime};
b.wasmMemory=H;b.ExitStatus=D;b.PThread=S;var Z;Q=function bb(){Z||cb();Z||(Q=bb)};
function cb(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!I)){u||W(qa);f(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(!u){if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();ra.unshift(c)}W(ra)}}}if(!(0<P))if(u)f(b),u||W(qa),postMessage({cmd:"loaded"});else{if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)sa();W(pa);0<P||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},
1);a()},1)):a())}}if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();cb();


  return JxlCodecModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JxlCodecModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JxlCodecModule; });
else if (typeof exports === 'object')
  exports["JxlCodecModule"] = JxlCodecModule;
