
var JxlCodecModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JxlCodecModule) {
  JxlCodecModule = JxlCodecModule || {};


function aa(){c.buffer!=g&&k(c.buffer);return ba}function n(){c.buffer!=g&&k(c.buffer);return ca}function p(){c.buffer!=g&&k(c.buffer);return da}function ea(){c.buffer!=g&&k(c.buffer);return fa}var r;r||(r=typeof JxlCodecModule !== 'undefined' ? JxlCodecModule : {});var u,v;r.ready=new Promise(function(a,b){u=a;v=b});
var ha=Object.assign({},r),w=(a,b)=>{throw b;},x="object"===typeof window,z="function"===typeof importScripts,A="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,B=r.ENVIRONMENT_IS_PTHREAD||!1,C="";function ia(a){return r.locateFile?r.locateFile(a,C):C+a}var D,E,F,fs,G,H;
if(A){C=z?require("path").dirname(C)+"/":__dirname+"/";H=()=>{G||(fs=require("fs"),G=require("path"))};D=function(b,d){H();b=G.normalize(b);return fs.readFileSync(b,d?void 0:"utf8")};F=b=>{b=D(b,!0);b.buffer||(b=new Uint8Array(b));return b};E=(b,d,e)=>{H();b=G.normalize(b);fs.readFile(b,function(f,h){f?e(f):d(h.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof I))throw b;});process.on("unhandledRejection",
function(b){throw b;});w=(b,d)=>{if(J())throw process.exitCode=b,d;d instanceof I||K("exiting due to exception: "+d);process.exit(b)};r.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(x||z)z?C=self.location.href:"undefined"!==typeof document&&document.currentScript&&(C=document.currentScript.src),
_scriptDir&&(C=_scriptDir),0!==C.indexOf("blob:")?C=C.substr(0,C.replace(/[?#].*/,"").lastIndexOf("/")+1):C="",A||(D=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(F=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),E=(a,b,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;
e.send(null)});A&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ja=console.log.bind(console),ka=console.warn.bind(console);A&&(H(),ja=a=>fs.writeSync(1,a+"\n"),ka=a=>fs.writeSync(2,a+"\n"));var la=r.print||ja,K=r.printErr||ka;Object.assign(r,ha);ha=null;r.quit&&(w=r.quit);var L,M;r.wasmBinary&&(M=r.wasmBinary);var noExitRuntime=r.noExitRuntime||!0;"object"!==typeof WebAssembly&&N("no native wasm support detected");var c,ma,O=!1;
function na(a){var b=new TextDecoder(a);this.decode=d=>{d.buffer instanceof SharedArrayBuffer&&(d=new Uint8Array(d));return b.decode.call(b,d)}}var oa="undefined"!==typeof TextDecoder?new na("utf8"):void 0;
function pa(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&oa)return oa.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var m=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|m:(f&7)<<18|h<<12|m<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function qa(a){return a?pa(n(),a,void 0):""}
"undefined"!==typeof TextDecoder&&new na("utf-16le");var g,ba,ca,da,fa;B&&(g=r.buffer);function k(a){g=a;r.HEAP8=ba=new Int8Array(a);r.HEAP16=new Int16Array(a);r.HEAP32=da=new Int32Array(a);r.HEAPU8=ca=new Uint8Array(a);r.HEAPU16=new Uint16Array(a);r.HEAPU32=new Uint32Array(a);r.HEAPF32=new Float32Array(a);r.HEAPF64=fa=new Float64Array(a)}var ra=r.INITIAL_MEMORY||16777216;
if(B)c=r.wasmMemory,g=r.buffer;else if(r.wasmMemory)c=r.wasmMemory;else if(c=new WebAssembly.Memory({initial:ra/65536,maximum:32768,shared:!0}),!(c.buffer instanceof SharedArrayBuffer))throw K("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),A&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");c&&(g=c.buffer);ra=g.byteLength;k(g);var sa,ta=[],P=[],ua=[],va=0;function J(){return noExitRuntime||0<va}function wa(){var a=r.preRun.shift();ta.unshift(a)}var Q=0,xa=null,R=null;r.preloadedImages={};r.preloadedAudios={};function N(a){if(B)postMessage({cmd:"onAbort",arg:a});else if(r.onAbort)r.onAbort(a);a="Aborted("+a+")";K(a);O=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");v(a);throw a;}
function ya(){return S.startsWith("data:application/octet-stream;base64,")}var S;S="jxl_emcc.wasm";ya()||(S=ia(S));function za(){var a=S;try{if(a==S&&M)return new Uint8Array(M);if(F)return F(a);throw"both async and sync fetching of the wasm failed";}catch(b){N(b)}}
function Aa(){if(!M&&(x||z)){if("function"===typeof fetch&&!S.startsWith("file://"))return fetch(S,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+S+"'";return a.arrayBuffer()}).catch(function(){return za()});if(E)return new Promise(function(a,b){E(S,function(d){a(new Uint8Array(d))},b)})}return Promise.resolve().then(function(){return za()})}var Ba={};
function T(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(r);else{var d=b.Ga;"number"===typeof d?void 0===b.U?Ca(d)():Ca(d)(b.U):d(void 0===b.U?null:b.U)}}}function Da(a){var b=Ea();a=a();Fa(b);return a}function Ga(a){var b=U.P[a];b&&(p()[a>>2]=0,U.ja(b.worker))}
var U={R:[],W:[],da:[],$:function(){B?U.wa():U.va()},va:function(){for(var a=0;4>a;++a)U.ea()},wa:function(){U.receiveObjectTransfer=U.ya;U.threadInit=U.la;U.setExitStatus=U.Aa;noExitRuntime=!1},P:{},Aa:function(){},ka:function(){for(var a in U.P){var b=U.P[a];b&&b.worker&&U.ja(b.worker)}for(a=0;a<U.R.length;++a)U.R[a].terminate();U.R=[]},ja:function(a){U.za(function(){delete U.P[a.S.ba];U.R.push(a);U.W.splice(U.W.indexOf(a),1);Ha(a.S.ba);a.S=void 0})},za:function(a){p()[Ia>>2]=0;try{a()}finally{p()[Ia>>
2]=1}},ya:function(){},la:function(){for(var a in U.da)U.da[a]()},ha:function(a,b){a.onmessage=d=>{d=d.data;var e=d.cmd;a.S&&(U.ra=a.S.ba);if(d.targetThread&&d.targetThread!=V()){var f=U.P[d.Ma];f?f.worker.postMessage(d,d.transferList):K('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Ja();else if("spawnThread"===e)Ka(d);else if("cleanupThread"===e)Ga(d.thread);else if("killThread"===
e)d=d.thread,p()[d>>2]=0,e=U.P[d],delete U.P[d],e.worker.terminate(),Ha(d),U.W.splice(U.W.indexOf(e.worker),1),e.worker.S=void 0;else if("cancelThread"===e)U.P[d.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===e)a.loaded=!0,b&&b(a),a.V&&(a.V(),delete a.V);else if("print"===e)la("Thread "+d.threadId+": "+d.text);else if("printErr"===e)K("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("setimmediate"===d.target)a.postMessage(d);else if("onAbort"===
e){if(r.onAbort)r.onAbort(d.arg)}else K("worker sent an unknown command "+e);U.ra=void 0};a.onerror=d=>{K("worker sent an error! "+d.filename+":"+d.lineno+": "+d.message);throw d;};A&&(a.on("message",function(d){a.onmessage({data:d})}),a.on("error",function(d){a.onerror(d)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:r.mainScriptUrlOrBlob||_scriptDir,wasmMemory:c,wasmModule:ma})},ea:function(){var a=ia("jxl_emcc.worker.js");U.R.push(new Worker(a))},ta:function(){0==U.R.length&&
(U.ea(),U.ha(U.R[0]));return U.R.pop()}};r.establishStackSpace=function(){var a=V(),b=p()[a+44>>2];a=p()[a+48>>2];La(b,b-a);Fa(b)};function Ma(a){if(B)return W(1,0,a);try{Na(a)}catch(b){b instanceof I||"unwind"==b||w(1,b)}}var X=[];function Ca(a){var b=X[a];b||(a>=X.length&&(X.length=a+1),X[a]=b=sa.get(a));return b}r.invokeEntryPoint=function(a,b){return Ca(a)(b)};var Oa;Oa=A?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:B?()=>performance.now()-r.__performance_now_clock_drift:()=>performance.now();
function Pa(a){this.T=a-16;this.qa=function(b){p()[this.T+4>>2]=b};this.na=function(b){p()[this.T+8>>2]=b};this.oa=function(){p()[this.T>>2]=0};this.ma=function(){var b=0;aa()[this.T+12>>0]=b};this.pa=function(){var b=0;aa()[this.T+13>>0]=b};this.$=function(b,d){this.qa(b);this.na(d);this.oa();this.ma();this.pa()}}var Qa=0;
function Ka(a){var b=U.ta();if(!b)return 6;U.W.push(b);var d=U.P[a.aa]={worker:b,ba:a.aa};b.S=d;var e={cmd:"run",start_routine:a.Ba,arg:a.U,threadInfoStruct:a.aa};b.V=()=>{e.time=performance.now();b.postMessage(e,a.Ca)};b.loaded&&(b.V(),delete b.V);return 0}function W(a,b){var d=arguments.length-2,e=arguments;return Da(function(){for(var f=Ra(8*d),h=f>>3,m=0;m<d;m++){var l=e[2+m];ea()[h+m]=l}return Sa(a,d,f,b)})}var Ta=[];
function Ua(a,b,d,e){Da(function(){var f=Ra(12),h=0;if(b){for(var m=h=0;m<b.length;++m){var l=b.charCodeAt(m);55296<=l&&57343>=l&&(l=65536+((l&1023)<<10)|b.charCodeAt(++m)&1023);127>=l?++h:h=2047>=l?h+2:65535>=l?h+3:h+4}var t=h+1;h=Y(t);m=n();l=h;if(0<t){t=l+t-1;for(var y=0;y<b.length;++y){var q=b.charCodeAt(y);if(55296<=q&&57343>=q){var eb=b.charCodeAt(++y);q=65536+((q&1023)<<10)|eb&1023}if(127>=q){if(l>=t)break;m[l++]=q}else{if(2047>=q){if(l+1>=t)break;m[l++]=192|q>>6}else{if(65535>=q){if(l+2>=
t)break;m[l++]=224|q>>12}else{if(l+3>=t)break;m[l++]=240|q>>18;m[l++]=128|q>>12&63}m[l++]=128|q>>6&63}m[l++]=128|q&63}}m[l]=0}}p()[f>>2]=h;p()[f+4>>2]=d;p()[f+8>>2]=e;Va(a,657457152,0,h,f)})}var Wa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Xa(a){a=2<a?qa(a):a;return Wa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ya(a,b,d){var e=Xa(a);if(!e)return-4;e.Z&&(p()[e.Z>>2]=b,p()[e.Z+4>>2]=d);if(e.ia||!e.Ea)e.ia&&(e=e.ia),a=!1,e.Y&&e.Y.X&&(a=e.Y.X.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=d,a&&e.Y.X.viewport(0,0,b,d);else return e.Z?(e=p()[e.Z+8>>2],a=a?qa(a):"",Ua(e,a,b,d),1):-4;return 0}function Za(a,b,d){return B?W(2,1,a,b,d):Ya(a,b,d)}
function $a(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(d,e){b.vertexAttribDivisorANGLE(d,e)},a.drawArraysInstanced=function(d,e,f,h){b.drawArraysInstancedANGLE(d,e,f,h)},a.drawElementsInstanced=function(d,e,f,h,m){b.drawElementsInstancedANGLE(d,e,f,h,m)})}
function ab(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(d){b.deleteVertexArrayOES(d)},a.bindVertexArray=function(d){b.bindVertexArrayOES(d)},a.isVertexArray=function(d){return b.isVertexArrayOES(d)})}function bb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(d,e){b.drawBuffersWEBGL(d,e)})}
function cb(a,b){a.ga||(a.ga=a.getContext,a.getContext=function(e,f){f=a.ga(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var d=a.getContext("webgl",b);return d?db(d,b):0}function db(a,b){var d=Y(8);p()[d+4>>2]=V();var e={Ha:d,attributes:b,version:b.xa,X:a};a.canvas&&(a.canvas.Y=e);("undefined"===typeof b.fa||b.fa)&&fb(e);return d}
function fb(a){a||(a=gb);if(!a.ua){a.ua=!0;var b=a.X;$a(b);ab(b);bb(b);b.Fa=b.getExtension("EXT_disjoint_timer_query");b.Ja=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(d){d.includes("lose_context")||d.includes("debug")||b.getExtension(d)})}}var gb,hb=["default","low-power","high-performance"],ib=[null,[],[]];function jb(a){return B?W(3,1,a):0}function kb(a,b,d,e,f){if(B)return W(4,1,a,b,d,e,f)}
function lb(a,b,d,e){if(B)return W(5,1,a,b,d,e);for(var f=0,h=0;h<d;h++){var m=p()[b>>2],l=p()[b+4>>2];b+=8;for(var t=0;t<l;t++){var y=n()[m+t],q=ib[a];0===y||10===y?((1===a?la:K)(pa(q,0)),q.length=0):q.push(y)}f+=l}p()[e>>2]=f;return 0}U.$();
var mb=[null,Ma,Za,jb,kb,lb],pb={u:function(a){return Y(a+16)+16},t:function(a,b,d){(new Pa(a)).$(b,d);Qa++;throw a;},s:function(a){nb(a,!z,1,!x);U.la()},g:function(a){B?postMessage({cmd:"cleanupThread",thread:a}):Ga(a)},d:function(a,b,d,e){if("undefined"===typeof SharedArrayBuffer)return K("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(B&&0===f.length)return ob(687865856,a,b,d,e);a={Ba:d,aa:a,U:e,Ca:f};return B?(a.Da="spawnThread",postMessage(a,
f),0):Ka(a)},r:function(){return 2097152},k:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(B)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=U.P[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){N("")},e:function(){A||z||(L||(L={}),L["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(L["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=
1,K("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},c:Oa,p:function(a,b,d){n().copyWithin(a,b,b+d)},h:function(a,b,d){Ta.length=b;d>>=3;for(var e=0;e<b;e++)Ta[e]=ea()[d+e];return(0>a?Ba[-a-1]:mb[a]).apply(null,Ta)},n:function(a){var b=n().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{c.grow(Math.min(2147483648,
e)-g.byteLength+65535>>>16);k(c.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},i:function(a,b,d){return Xa(a)?Ya(a,b,d):Za(a,b,d)},l:function(){throw"unwind";},j:function(a,b){b>>=2;var d=p()[b+6];b={alpha:!!p()[b],depth:!!p()[b+1],stencil:!!p()[b+2],antialias:!!p()[b+3],premultipliedAlpha:!!p()[b+4],preserveDrawingBuffer:!!p()[b+5],powerPreference:hb[d],failIfMajorPerformanceCaveat:!!p()[b+7],xa:p()[b+8],Ia:p()[b+9],fa:p()[b+10],sa:p()[b+11],Ka:p()[b+12],La:p()[b+13]};a=Xa(a);
return!a||b.sa?0:cb(a,b)},q:function(a){Na(a)},o:jb,m:kb,f:lb,a:c||r.wasmMemory};
(function(){function a(f,h){r.asm=f.exports;U.da.push(r.asm.A);sa=r.asm.y;P.unshift(r.asm.v);ma=h;if(!B){var m=U.R.length;U.R.forEach(function(l){U.ha(l,function(){if(!--m&&(Q--,r.monitorRunDependencies&&r.monitorRunDependencies(Q),0==Q&&(null!==xa&&(clearInterval(xa),xa=null),R))){var t=R;R=null;t()}})})}}function b(f){a(f.instance,f.module)}function d(f){return Aa().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(f,function(h){K("failed to asynchronously prepare wasm: "+
h);N(h)})}var e={a:pb};B||(Q++,r.monitorRunDependencies&&r.monitorRunDependencies(Q));if(r.instantiateWasm)try{return r.instantiateWasm(e,a)}catch(f){return K("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return M||"function"!==typeof WebAssembly.instantiateStreaming||ya()||S.startsWith("file://")||"function"!==typeof fetch?d(b):fetch(S,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(h){K("wasm streaming compile failed: "+
h);K("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(v);return{}})();r.___wasm_call_ctors=function(){return(r.___wasm_call_ctors=r.asm.v).apply(null,arguments)};r._jxlDecompress=function(){return(r._jxlDecompress=r.asm.w).apply(null,arguments)};var Y=r._malloc=function(){return(Y=r._malloc=r.asm.x).apply(null,arguments)};r._free=function(){return(r._free=r.asm.z).apply(null,arguments)};r._emscripten_tls_init=function(){return(r._emscripten_tls_init=r.asm.A).apply(null,arguments)};
r.__emscripten_thread_crashed=function(){return(r.__emscripten_thread_crashed=r.asm.B).apply(null,arguments)};var nb=r.__emscripten_thread_init=function(){return(nb=r.__emscripten_thread_init=r.asm.C).apply(null,arguments)},V=r._pthread_self=function(){return(V=r._pthread_self=r.asm.D).apply(null,arguments)},Ja=r._emscripten_main_thread_process_queued_calls=function(){return(Ja=r._emscripten_main_thread_process_queued_calls=r.asm.E).apply(null,arguments)};
r._emscripten_current_thread_process_queued_calls=function(){return(r._emscripten_current_thread_process_queued_calls=r.asm.F).apply(null,arguments)};
var ob=r._emscripten_sync_run_in_main_thread_4=function(){return(ob=r._emscripten_sync_run_in_main_thread_4=r.asm.G).apply(null,arguments)},Sa=r._emscripten_run_in_main_runtime_thread_js=function(){return(Sa=r._emscripten_run_in_main_runtime_thread_js=r.asm.H).apply(null,arguments)},Va=r._emscripten_dispatch_to_thread_=function(){return(Va=r._emscripten_dispatch_to_thread_=r.asm.I).apply(null,arguments)},Ha=r.__emscripten_thread_free_data=function(){return(Ha=r.__emscripten_thread_free_data=r.asm.J).apply(null,
arguments)};r.__emscripten_thread_exit=function(){return(r.__emscripten_thread_exit=r.asm.K).apply(null,arguments)};
var La=r._emscripten_stack_set_limits=function(){return(La=r._emscripten_stack_set_limits=r.asm.L).apply(null,arguments)},Ea=r.stackSave=function(){return(Ea=r.stackSave=r.asm.M).apply(null,arguments)},Fa=r.stackRestore=function(){return(Fa=r.stackRestore=r.asm.N).apply(null,arguments)},Ra=r.stackAlloc=function(){return(Ra=r.stackAlloc=r.asm.O).apply(null,arguments)},Ia=r.__emscripten_allow_main_runtime_queued_calls=38192;r.keepRuntimeAlive=J;r.PThread=U;r.PThread=U;r.wasmMemory=c;r.ExitStatus=I;
var Z;function I(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}R=function qb(){Z||rb();Z||(R=qb)};
function rb(){function a(){if(!Z&&(Z=!0,r.calledRun=!0,!O)){B||T(P);u(r);if(r.onRuntimeInitialized)r.onRuntimeInitialized();if(!B){if(r.postRun)for("function"==typeof r.postRun&&(r.postRun=[r.postRun]);r.postRun.length;){var b=r.postRun.shift();ua.unshift(b)}T(ua)}}}if(!(0<Q))if(B)u(r),B||T(P),postMessage({cmd:"loaded"});else{if(r.preRun)for("function"==typeof r.preRun&&(r.preRun=[r.preRun]);r.preRun.length;)wa();T(ta);0<Q||(r.setStatus?(r.setStatus("Running..."),setTimeout(function(){setTimeout(function(){r.setStatus("")},
1);a()},1)):a())}}r.run=rb;function Na(a){if(B)throw Ma(a),"unwind";J()||B||U.ka();if(!J()){U.ka();if(r.onExit)r.onExit(a);O=!0}w(a,new I(a))}if(r.preInit)for("function"==typeof r.preInit&&(r.preInit=[r.preInit]);0<r.preInit.length;)r.preInit.pop()();rb();


  return JxlCodecModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JxlCodecModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JxlCodecModule; });
else if (typeof exports === 'object')
  exports["JxlCodecModule"] = JxlCodecModule;
